-- Rebirth is now an instance-based ScreenGui: StarterGui.RebirthGui (built live in Studio)
-- plus its child "Controller" LocalScript, which registers the "Rebirth" modal in
-- ReactModalRegistry and drives the dynamic data (Beli/ship progress, rewards, rebirth button).
--
-- The previous React implementation (RebirthScreen + this mount) has been retired so the two
-- don't both register the "Rebirth" modal. This file is intentionally a no-op.
