-- The Robux Shop is now an instance-based ScreenGui: StarterGui.RobuxShopGui plus its
-- child "Controller" LocalScript, which registers the "Store" modal in ReactModalRegistry
-- and reuses the existing PurchaseAdapter (so the gamepass / dev-product purchase flow,
-- prices and ownership states are unchanged).
--
-- The previous React implementation (ShopShell mount) has been retired so the two don't
-- both register the "Store" modal. This file is intentionally a no-op.
