-- The Upgrade (SpeedUpgrade) menu is now an instance-based ScreenGui: StarterGui.UpgradeGui
-- plus its child "Controller" LocalScript, which registers the "SpeedUpgrade" modal in
-- ReactModalRegistry (so the Franky "Talk to Franky" prompt opens it) and reuses the same
-- SpeedUpgrade config + BuySpeedUpgrade remote / Robux developer-product purchase flow.
--
-- The previous React implementation (SpeedUpgradeScreen via ReactFrameModalAdapter) has been
-- retired so the two don't both register the "SpeedUpgrade" modal. This file is intentionally
-- a no-op.
