local Catalog = {}

local function item(config)
	return config
end

local items = {
	starterBundle = item({
		id = "starter-bundle",
		sectionKey = "bundles",
		title = "Starter Bundle",
		description = "A clean first-crew pickup with Beli, chest fuel, and a smooth launch into your opening runs.",
		priceText = "299",
		badge = "New",
		themeKey = "Gold",
		iconText = "SB",
		callToAction = "Set Sail",
		highlights = {
			"Starter-ready stash",
			"Fast early momentum",
		},
		purchase = {
			kind = "stub",
		},
	}),
	pirateProgressBundle = item({
		id = "pirate-progress-bundle",
		sectionKey = "bundles",
		title = "Pirate Progress Bundle",
		description = "Push your captain build forward with boosted earnings, cargo support, and premium utility built for longer sessions.",
		priceText = "699",
		badge = "Best Value",
		timerText = "Ends in 18h 42m",
		themeKey = "Crimson",
		iconText = "PP",
		callToAction = "Claim Offer",
		highlights = {
			"Premium utility mix",
			"Built for steady progression",
		},
		purchase = {
			kind = "stub",
		},
	}),
	fruitHunterBundle = item({
		id = "fruit-hunter-bundle",
		sectionKey = "bundles",
		title = "Fruit Hunter Bundle",
		description = "A hunter-focused haul with tracking help, chest support, and a lineup tuned for chasing better fruit spawns.",
		priceText = "849",
		badge = "Limited",
		timerText = "Refreshes in 07h 09m",
		themeKey = "Violet",
		iconText = "FH",
		callToAction = "Track Loot",
		highlights = {
			"Great for fruit routes",
			"Includes premium hunt tools",
		},
		purchase = {
			kind = "stub",
		},
	}),
	seaBeastSupplyCrate = item({
		id = "sea-beast-supply-crate",
		sectionKey = "bundles",
		title = "Sea Beast Supply Crate",
		description = "Stack up run support, extraction comforts, and a heavy chest curve for high-pressure sea lanes.",
		priceText = "499",
		badge = "Popular",
		themeKey = "Cyan",
		iconText = "SC",
		callToAction = "Open Crate",
		purchase = {
			kind = "stub",
		},
	}),
	vip = item({
		id = "vip",
		sectionKey = "gamepasses",
		title = "VIP",
		description = "Get a VIP tag, route shortcuts, and a Beli edge that fits Grand Line Rush's premium lane.",
		priceText = "...",
		badge = "Popular",
		themeKey = "Emerald",
		iconText = "VIP",
		callToAction = "Unlock VIP",
		highlights = {
			"Permanent access boost",
			"Premium captain perks",
		},
		purchase = {
			kind = "gamepass",
			id = 1667049739,
			ownedKey = "VIP",
		},
	}),
	twoXMoney = item({
		id = "x2-doubloons",
		sectionKey = "gamepasses",
		title = "2x Beli",
		description = "Permanent double Beli pacing for players who want faster crew and ship progression.",
		priceText = "...",
		badge = "Best Value",
		themeKey = "Gold",
		iconText = "2X",
		callToAction = "Double Up",
		purchase = {
			kind = "gamepass",
			id = 1667343349,
			ownedKey = "x2 Money",
		},
	}),
	privateServers = item({
		id = "private-servers",
		sectionKey = "gamepasses",
		title = "Private Servers",
		description = "Spin up quieter seas for crew sessions, route testing, and farming with your own pace and rules.",
		priceText = "399",
		badge = "Popular",
		themeKey = "Slate",
		iconText = "PS",
		callToAction = "Soon",
		purchase = {
			kind = "stub",
		},
	}),
	crewUtilityPass = item({
		id = "crew-utility-pass",
		sectionKey = "gamepasses",
		title = "Crew Utility Pass",
		description = "Keep your crew setup cleaner with premium utility perks, smoother deck management, and faster prep between runs.",
		priceText = "349",
		badge = "New",
		themeKey = "Orange",
		iconText = "CU",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	extraLoadoutSlot = item({
		id = "extra-loadout-slot",
		sectionKey = "products",
		title = "Extra Loadout Slot",
		description = "Keep one more fruit or deck plan ready to swap into your route without breaking momentum.",
		priceText = "129",
		badge = "Popular",
		themeKey = "Cyan",
		iconText = "LS",
		callToAction = "Soon",
		purchase = {
			kind = "stub",
		},
	}),
	inventoryExpansion = item({
		id = "inventory-expansion",
		sectionKey = "products",
		title = "Inventory Expansion",
		description = "Expand your hold for extra fruit finds, run rewards, and utility stock without constant cleanup.",
		priceText = "249",
		badge = "New",
		themeKey = "Emerald",
		iconText = "IE",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	chestBundle = item({
		id = "chest-bundle",
		sectionKey = "products",
		title = "Chest Bundle",
		description = "A crate burst tuned for players who want more reward rolls and smoother route-to-base conversion.",
		priceText = "219",
		badge = "Popular",
		themeKey = "Gold",
		iconText = "CB",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	fruitCompass = item({
		id = "fruit-compass",
		sectionKey = "products",
		title = "Fruit Compass",
		description = "Keep a sharper line on rare fruit routes with premium guidance, hunt nudges, and smarter chase planning.",
		priceText = "299",
		badge = "Limited",
		timerText = "Launch window",
		themeKey = "Violet",
		iconText = "FC",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	captainTitlePack = item({
		id = "captain-title-pack",
		sectionKey = "products",
		title = "Captain Title Pack",
		description = "Show off your captain style with premium title flair, sharp calling cards, and standout profile polish.",
		priceText = "149",
		badge = "New",
		themeKey = "Crimson",
		iconText = "CT",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	shipTrailSet = item({
		id = "ship-trail-set",
		sectionKey = "products",
		title = "Ship Trail Set",
		description = "Dress your wake with premium ocean trails, brighter exhaust colors, and extra ship-side flair.",
		priceText = "179",
		badge = "Popular",
		themeKey = "Orange",
		iconText = "ST",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	rewardsBoost = item({
		id = "rewards-boost",
		sectionKey = "boosts",
		title = "2x Rewards Boost",
		description = "A live Beli surge for 30 minutes when you want a clean power session or a focused grind block.",
		priceText = "...",
		badge = "Popular",
		themeKey = "Cyan",
		iconText = "RB",
		callToAction = "Boost Now",
		purchase = {
			kind = "product",
			id = 3515417573,
		},
	}),
	rewardsBoostTriple = item({
		id = "rewards-boost-x3",
		sectionKey = "boosts",
		title = "2x Rewards Boost x3",
		description = "Three stacked reward charges for captains who want longer runs and less shop micromanagement.",
		priceText = "...",
		badge = "Best Value",
		themeKey = "Gold",
		iconText = "3X",
		callToAction = "Stock Up",
		purchase = {
			kind = "product",
			id = 3515418047,
		},
	}),
	dropRateBoost = item({
		id = "drop-rate-boost",
		sectionKey = "boosts",
		title = "Drop Rate Boost",
		description = "Live server luck for 15 minutes to tilt fruit and drop odds when the whole lobby wants better chances.",
		priceText = "...",
		badge = "Limited",
		timerText = "15m server pulse",
		themeKey = "Violet",
		iconText = "DR",
		callToAction = "Raise Luck",
		purchase = {
			kind = "product",
			id = 3515409012,
		},
	}),
	crewXpSurge = item({
		id = "crew-xp-surge",
		sectionKey = "boosts",
		title = "Crew XP Surge",
		description = "Kick your crew into faster training with a timed experience surge built for focused progression sessions.",
		priceText = "159",
		badge = "New",
		themeKey = "Emerald",
		iconText = "XP",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	doubloonPack = item({
		id = "doubloon-pack",
		sectionKey = "currency",
		title = "Beli Pack",
		description = "A quick Beli pickup for small upgrades, rerolls, and convenience buys before your next run.",
		priceText = "79",
		badge = "New",
		themeKey = "Gold",
		iconText = "DP",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	captainsStash = item({
		id = "captains-stash",
		sectionKey = "currency",
		title = "Captain's Stash",
		description = "A mid-tier Beli reserve for players tuning ship loadouts and premium deck prep.",
		priceText = "249",
		badge = "Popular",
		themeKey = "Orange",
		iconText = "CS",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	fleetReserve = item({
		id = "fleet-reserve",
		sectionKey = "currency",
		title = "Fleet Reserve",
		description = "A large treasury drop for captains planning longer optimization pushes, ship upgrades, and team sessions.",
		priceText = "599",
		badge = "Best Value",
		themeKey = "Crimson",
		iconText = "FR",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	portTreasury = item({
		id = "port-treasury",
		sectionKey = "currency",
		title = "Port Treasury",
		description = "A premium treasury haul for captains planning elite upgrades, event prep, and heavy reroll sessions.",
		priceText = "999",
		badge = "Limited",
		timerText = "Event stock",
		themeKey = "Slate",
		iconText = "PT",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	autoExtract = item({
		id = "auto-extract-charter",
		sectionKey = "utility",
		title = "Auto Extract Charter",
		description = "Speed up chest turn-ins and keep your route moving with smoother extraction support between sea runs.",
		priceText = "269",
		badge = "New",
		themeKey = "Cyan",
		iconText = "AE",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	deckPreset = item({
		id = "deck-preset-slot",
		sectionKey = "utility",
		title = "Deck Preset Slot",
		description = "Save one more route-ready deck setup and switch between farming plans with less menu overhead.",
		priceText = "189",
		badge = "Popular",
		themeKey = "Slate",
		iconText = "DS",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	crewCallBell = item({
		id = "crew-call-bell",
		sectionKey = "utility",
		title = "Crew Call Bell",
		description = "Rally your crew faster with a handy coordination tool built for smoother team-side sessions and quicker regrouping.",
		priceText = "119",
		badge = "New",
		themeKey = "Emerald",
		iconText = "CB",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
	runRecoveryToken = item({
		id = "run-recovery-token",
		sectionKey = "utility",
		title = "Run Recovery Token",
		description = "Protect a hard-fought voyage with a recovery tool meant to soften rough losses and keep your momentum alive.",
		priceText = "229",
		badge = "Limited",
		timerText = "Seasonal hook",
		themeKey = "Orange",
		iconText = "RT",
		callToAction = "Coming Soon",
		purchase = {
			kind = "stub",
		},
	}),
}

Catalog.title = "Grand Line Rush Shop"
Catalog.subtitle = "Stock your captain with premium bundles, boosts, and voyage perks before the next run."
Catalog.heroEyebrow = "Grand Market"
Catalog.heroHeadline = "Stock up before you sail back into the Grand Line."
Catalog.heroCopy = "Grab featured bundles, permanent captain perks, and limited boosts built for faster routes, stronger hauls, and smoother progression."
Catalog.codesPanel = {
	title = "Redeem Codes",
	eyebrow = "Signal Snail Drops",
	description = "Enter event, update, or community codes here to claim bonus rewards when a valid drop is active.",
	placeholder = "Enter a Grand Line Rush code",
	helperText = "Codes are case-sensitive and usually arrive through updates, socials, or limited-time events.",
	buttonText = "Redeem",
}

Catalog.featuredOffers = {
	items.pirateProgressBundle,
	items.vip,
	items.dropRateBoost,
}

Catalog.sections = {
	{
		key = "bundles",
		title = "Bundles",
		eyebrow = "Top Offers",
		description = "High-value packs for first runs, fruit hunting, and longer progression pushes across the sea.",
		themeKey = "Crimson",
		items = {
			items.starterBundle,
			items.pirateProgressBundle,
			items.fruitHunterBundle,
			items.seaBeastSupplyCrate,
		},
	},
	{
		key = "gamepasses",
		title = "Game Passes",
		eyebrow = "Permanent Upgrades",
		description = "Permanent captain perks that stay with your account and keep every voyage a little smoother.",
		themeKey = "Emerald",
		items = {
			items.vip,
			items.twoXMoney,
			items.privateServers,
			items.crewUtilityPass,
		},
	},
	{
		key = "products",
		title = "Products",
		eyebrow = "Convenience Picks",
		description = "Quick pickups for cargo room, hunting support, cosmetic flair, and route-friendly extras.",
		themeKey = "Cyan",
		items = {
			items.extraLoadoutSlot,
			items.inventoryExpansion,
			items.chestBundle,
			items.fruitCompass,
			items.captainTitlePack,
			items.shipTrailSet,
		},
	},
	{
		key = "boosts",
		title = "Boosts",
		eyebrow = "Live Power Ups",
		description = "Timed power-ups for reward sessions, fruit hunts, and high-pressure farming windows.",
		themeKey = "Gold",
		items = {
			items.rewardsBoost,
			items.rewardsBoostTriple,
			items.dropRateBoost,
			items.crewXpSurge,
		},
	},
	{
		key = "currency",
		title = "Currency",
		eyebrow = "Treasury",
		description = "Treasury packs for captains saving up for rerolls, upgrades, and premium convenience buys.",
		themeKey = "Orange",
		items = {
			items.doubloonPack,
			items.captainsStash,
			items.fleetReserve,
			items.portTreasury,
		},
	},
	{
		key = "utility",
		title = "Utility",
		eyebrow = "Captain Tools",
		description = "Quality-of-life tools that keep deck management, route prep, and crew sessions feeling clean.",
		themeKey = "Slate",
		items = {
			items.autoExtract,
			items.deckPreset,
			items.crewCallBell,
			items.runRecoveryToken,
		},
	},
}

return Catalog
