local ReplicatedStorage = game:GetService("ReplicatedStorage")

local GamepassesConfig =
	require(ReplicatedStorage:WaitForChild("Modules"):WaitForChild("Configs"):WaitForChild("Gamepasses"))

local Catalog = {}
local VIP_GAMEPASS_ID =
	assert(tonumber(GamepassesConfig.VIP and GamepassesConfig.VIP.ID), "VIP gamepass ID is not configured")
local VIP_ICON = tostring(GamepassesConfig.VIP and GamepassesConfig.VIP.Icon or "")

local function item(config)
	config.description = config.subtitle
	config.priceText = config.priceText or "Soon"
	config.callToAction = config.callToAction or "Coming Soon"
	config.purchase = config.purchase or {
		kind = "stub",
	}
	return config
end

local items = {
	limitedVoyagePack = item({
		id = "limited-voyage-pack",
		sectionKey = "featured",
		title = "Limited Voyage Pack",
		subtitle = "Launch bundle",
		tags = { "Limited", "Bundle", "Value" },
		themeKey = "Crimson",
		iconText = "LV",
	}),
	starterPack = item({
		id = "starter-pack",
		sectionKey = "bundles",
		title = "Starter Pack",
		subtitle = "First boost",
		tags = { "Bundle", "New" },
		themeKey = "Gold",
		iconText = "SP",
	}),
	raiderPack = item({
		id = "raider-pack",
		sectionKey = "bundles",
		title = "Raider Pack",
		subtitle = "Raid ready",
		tags = { "Bundle", "Raid" },
		themeKey = "Orange",
		iconText = "RP",
	}),
	emperorPack = item({
		id = "emperor-pack",
		sectionKey = "bundles",
		title = "Emperor Pack",
		subtitle = "Premium haul",
		tags = { "Bundle", "Best" },
		themeKey = "Violet",
		iconText = "EP",
	}),
	captainsPass = item({
		id = "captains-pass",
		sectionKey = "vip",
		title = "Captain's Pass",
		subtitle = "Permanent perks",
		tags = { "VIP", "Permanent" },
		priceText = "...",
		callToAction = "Unlock",
		themeKey = "Emerald",
		iconText = "VIP",
		iconImage = VIP_ICON,
		purchase = {
			kind = "gamepass",
			id = VIP_GAMEPASS_ID,
			ownedKey = "VIP",
		},
	}),
	commonDfChest = item({
		id = "common-df-chest",
		sectionKey = "fruit-chests",
		title = "Common DF Chest",
		subtitle = "Starter fruit roll",
		tags = { "Chest", "Common" },
		themeKey = "Cyan",
		iconText = "DF",
		RequiresPaidRandomItemPolicy = true,
		PaidRandomItem = true,
	}),
	legendaryDfCrate = item({
		id = "legendary-df-crate",
		sectionKey = "fruit-chests",
		title = "Legendary DF Crate",
		subtitle = "High rarity chance",
		tags = { "Crate", "Legendary" },
		themeKey = "Gold",
		iconText = "LD",
		RequiresPaidRandomItemPolicy = true,
		PaidRandomItem = true,
	}),
	mythicDfCrate = item({
		id = "mythic-df-crate",
		sectionKey = "fruit-chests",
		title = "Mythic DF Crate",
		subtitle = "Best mythic chance",
		tags = { "Crate", "Mythic" },
		themeKey = "Violet",
		iconText = "MD",
		RequiresPaidRandomItemPolicy = true,
		PaidRandomItem = true,
	}),
	basicReroll = item({
		id = "basic-reroll",
		sectionKey = "fruit-chests",
		title = "Basic Reroll",
		subtitle = "Fresh roll",
		tags = { "Reroll", "Basic" },
		themeKey = "Cyan",
		iconText = "BR",
		RequiresPaidRandomItemPolicy = true,
		RandomRewardGenerator = true,
	}),
	legendaryReroll = item({
		id = "legendary-reroll",
		sectionKey = "fruit-chests",
		title = "Legendary Reroll",
		subtitle = "Better odds",
		tags = { "Reroll", "Legendary" },
		themeKey = "Gold",
		iconText = "LR",
		RequiresPaidRandomItemPolicy = true,
		RandomRewardGenerator = true,
	}),
	mythicReroll = item({
		id = "mythic-reroll",
		sectionKey = "fruit-chests",
		title = "Mythic Reroll",
		subtitle = "Top odds",
		tags = { "Reroll", "Mythic" },
		themeKey = "Violet",
		iconText = "MR",
		RequiresPaidRandomItemPolicy = true,
		RandomRewardGenerator = true,
	}),
	goldSurge15 = item({
		id = "gold-surge-15",
		sectionKey = "boosts",
		title = "Gold Surge 15 min",
		subtitle = "2x money",
		tags = { "Boost", "15m" },
		themeKey = "Gold",
		iconText = "2X",
	}),
	goldSurge60 = item({
		id = "gold-surge-60",
		sectionKey = "boosts",
		title = "Gold Surge 60 min",
		subtitle = "2x money",
		tags = { "Boost", "60m" },
		themeKey = "Gold",
		iconText = "2X",
	}),
	fortuneTide15 = item({
		id = "fortune-tide-15",
		sectionKey = "boosts",
		title = "Fortune Tide 15 min",
		subtitle = "Rare boost",
		tags = { "Luck", "15m" },
		themeKey = "Violet",
		iconText = "FT",
		RequiresPaidRandomItemPolicy = true,
		RandomRewardGenerator = true,
	}),
	fortuneTide60 = item({
		id = "fortune-tide-60",
		sectionKey = "boosts",
		title = "Fortune Tide 60 min",
		subtitle = "Rare boost",
		tags = { "Luck", "60m" },
		themeKey = "Violet",
		iconText = "FT",
		RequiresPaidRandomItemPolicy = true,
		RandomRewardGenerator = true,
	}),
	treasureSense15 = item({
		id = "treasure-sense-15",
		sectionKey = "boosts",
		title = "Treasure Sense 15 min",
		subtitle = "Find loot",
		tags = { "Sense", "15m" },
		themeKey = "Cyan",
		iconText = "TS",
	}),
	treasureSense60 = item({
		id = "treasure-sense-60",
		sectionKey = "boosts",
		title = "Treasure Sense 60 min",
		subtitle = "Find loot",
		tags = { "Sense", "60m" },
		themeKey = "Cyan",
		iconText = "TS",
	}),
	treasureSense30 = item({
		id = "treasure-sense-30",
		sectionKey = "raiding",
		title = "Treasure Sense 30 min",
		subtitle = "Find loot",
		tags = { "Sense", "30m" },
		themeKey = "Cyan",
		iconText = "TS",
	}),
	guardBarrier = item({
		id = "guard-barrier",
		sectionKey = "protection",
		title = "Guard Barrier",
		subtitle = "Protect haul",
		tags = { "Shield", "Safety" },
		themeKey = "Emerald",
		iconText = "GB",
	}),
	returnBeacon = item({
		id = "return-beacon",
		sectionKey = "protection",
		title = "Return Beacon",
		subtitle = "Emergency exit",
		tags = { "Escape", "Safety" },
		themeKey = "Cyan",
		iconText = "RB",
	}),
	extraCharge = item({
		id = "extra-charge",
		sectionKey = "protection",
		title = "Extra Charge",
		subtitle = "More uses",
		tags = { "Charge", "Utility" },
		themeKey = "Orange",
		iconText = "EC",
	}),
	vaultSealOne = item({
		id = "vault-seal-1",
		sectionKey = "protection",
		title = "Vault Seal I",
		subtitle = "Lock crewmate",
		tags = { "Seal", "I" },
		themeKey = "Slate",
		iconText = "V1",
	}),
	vaultSealTwo = item({
		id = "vault-seal-2",
		sectionKey = "protection",
		title = "Vault Seal II",
		subtitle = "Lock crewmate",
		tags = { "Seal", "II" },
		themeKey = "Violet",
		iconText = "V2",
	}),
	raidMark = item({
		id = "raid-mark",
		sectionKey = "raiding",
		title = "Raid Mark",
		subtitle = "Start raid",
		tags = { "Raid", "1x" },
		themeKey = "Crimson",
		iconText = "RM",
	}),
	raidMarksThree = item({
		id = "raid-marks-3",
		sectionKey = "raiding",
		title = "Raid Marks x3",
		subtitle = "More raids",
		tags = { "Raid", "3x" },
		themeKey = "Orange",
		iconText = "3R",
	}),
	bronzeRaider = item({
		id = "bronze-raider",
		sectionKey = "cosmetics",
		title = "Bronze Raider",
		subtitle = "Ship skin",
		tags = { "Skin", "Bronze" },
		themeKey = "Orange",
		iconText = "BR",
	}),
	goldenGalleon = item({
		id = "golden-galleon",
		sectionKey = "cosmetics",
		title = "Golden Galleon",
		subtitle = "Ship skin",
		tags = { "Skin", "Gold" },
		themeKey = "Gold",
		iconText = "GG",
	}),
	phantomShip = item({
		id = "phantom-ship",
		sectionKey = "cosmetics",
		title = "Phantom Ship",
		subtitle = "Ship skin",
		tags = { "Skin", "Rare" },
		themeKey = "Violet",
		iconText = "PS",
	}),
	simpleAura = item({
		id = "simple-aura",
		sectionKey = "cosmetics",
		title = "Simple Aura",
		subtitle = "Soft glow",
		tags = { "Aura", "Basic" },
		themeKey = "Cyan",
		iconText = "SA",
	}),
	enhancedAura = item({
		id = "enhanced-aura",
		sectionKey = "cosmetics",
		title = "Enhanced Aura",
		subtitle = "Bright glow",
		tags = { "Aura", "Plus" },
		themeKey = "Emerald",
		iconText = "EA",
	}),
	mythicAura = item({
		id = "mythic-aura",
		sectionKey = "cosmetics",
		title = "Mythic Aura",
		subtitle = "Mythic glow",
		tags = { "Aura", "Mythic" },
		themeKey = "Violet",
		iconText = "MA",
	}),
	seaEmperorTitle = item({
		id = "sea-emperor-title",
		sectionKey = "cosmetics",
		title = "Sea Emperor Title",
		subtitle = "Name flair",
		tags = { "Title", "Royal" },
		themeKey = "Cyan",
		iconText = "SE",
	}),
	crimsonKingTitle = item({
		id = "crimson-king-title",
		sectionKey = "cosmetics",
		title = "Crimson King Title",
		subtitle = "Name flair",
		tags = { "Title", "Crimson" },
		themeKey = "Crimson",
		iconText = "CK",
	}),
	goldPedestal = item({
		id = "gold-pedestal",
		sectionKey = "cosmetics",
		title = "Gold Pedestal",
		subtitle = "Display stand",
		tags = { "Pedestal", "Gold" },
		themeKey = "Gold",
		iconText = "GP",
	}),
	mythicPedestal = item({
		id = "mythic-pedestal",
		sectionKey = "cosmetics",
		title = "Mythic Pedestal",
		subtitle = "Display stand",
		tags = { "Pedestal", "Mythic" },
		themeKey = "Violet",
		iconText = "MP",
	}),
}

Catalog.title = "Robux Shop"

Catalog.featuredSections = {
	{
		key = "featured-packs",
		title = "Featured Packs",
		themeKey = "Crimson",
		items = {
			items.limitedVoyagePack,
			items.starterPack,
		},
	},
	{
		key = "featured-perks",
		title = "Captain Perks",
		themeKey = "Emerald",
		items = {
			items.captainsPass,
		},
	},
	{
		key = "featured-chests",
		title = "Fruit Spotlight",
		themeKey = "Violet",
		items = {
			items.mythicDfCrate,
		},
	},
}

Catalog.sections = {
	{
		key = "bundles",
		title = "Bundles",
		themeKey = "Crimson",
		items = {
			items.starterPack,
			items.raiderPack,
			items.emperorPack,
		},
	},
	{
		key = "fruit-chests",
		title = "Fruit Chests",
		themeKey = "Violet",
		items = {
			items.commonDfChest,
			items.legendaryDfCrate,
			items.mythicDfCrate,
			items.basicReroll,
			items.legendaryReroll,
			items.mythicReroll,
		},
	},
	{
		key = "boosts",
		title = "Boosts",
		themeKey = "Gold",
		items = {
			items.goldSurge15,
			items.goldSurge60,
			items.fortuneTide15,
			items.fortuneTide60,
			items.treasureSense15,
			items.treasureSense60,
		},
	},
	{
		key = "protection",
		title = "Protection",
		themeKey = "Emerald",
		items = {
			items.guardBarrier,
			items.returnBeacon,
			items.extraCharge,
			items.vaultSealOne,
			items.vaultSealTwo,
		},
	},
	{
		key = "raiding",
		title = "Raiding",
		themeKey = "Crimson",
		items = {
			items.raidMark,
			items.raidMarksThree,
			items.treasureSense30,
		},
	},
	{
		key = "cosmetics",
		title = "Cosmetics",
		themeKey = "Cyan",
		items = {
			items.bronzeRaider,
			items.goldenGalleon,
			items.phantomShip,
			items.simpleAura,
			items.enhancedAura,
			items.mythicAura,
			items.seaEmperorTitle,
			items.crimsonKingTitle,
			items.goldPedestal,
			items.mythicPedestal,
		},
	},
	{
		key = "vip",
		title = "VIP",
		themeKey = "Emerald",
		items = {
			items.captainsPass,
		},
	},
}

return Catalog
