return {
	{
		Id = "weekly_extract_crew",
		Category = "Weekly",
		Name = "Crew Drive",
		Description = "Extract 8 crew members from corridor runs.",
		Objective = { Type = "ExtractCrew", Target = 8 },
		Rewards = {
			{ Type = "Currency", Amount = 1000 },
			{ Type = "Food", Key = "Meat", Amount = 4 },
			{ Type = "Material", Key = "Iron", Amount = 2 },
		},
	},
	{
		Id = "weekly_open_chests",
		Category = "Weekly",
		Name = "Cargo Audit",
		Description = "Open 12 treasure chests.",
		Objective = { Type = "OpenChest", Target = 12 },
		Rewards = {
			{ Type = "Currency", Amount = 700 },
			{ Type = "Food", Key = "Rice", Amount = 6 },
			{ Type = "Material", Key = "Timber", Amount = 12 },
		},
	},
	{
		Id = "weekly_reach_deep",
		Category = "Weekly",
		Name = "Deep Water Run",
		Description = "Extract 3 rewards from Deep depth or deeper.",
		Objective = { Type = "ReachDepth", Target = 3, DepthBand = "Deep" },
		Rewards = {
			{ Type = "Material", Key = "Iron", Amount = 5 },
			{ Type = "Food", Key = "SeaBeastMeat", Amount = 1 },
		},
	},
	{
		Id = "weekly_train_crew",
		Category = "Weekly",
		Name = "Crew Drills",
		Description = "Gain 5 crew levels by feeding crew members.",
		Objective = { Type = "UpgradeCrew", Target = 5 },
		Rewards = {
			{ Type = "Currency", Amount = 800 },
			{ Type = "Food", Key = "Meat", Amount = 3 },
		},
	},
	{
		Id = "weekly_ship_fund",
		Category = "Weekly",
		Name = "Ship Treasury",
		Description = "Collect 2,500 Beli from support systems.",
		Objective = { Type = "EarnBeli", Target = 2500 },
		Rewards = {
			{ Type = "Currency", Amount = 900 },
			{ Type = "Food", Key = "Apple", Amount = 8 },
			{ Type = "Material", Key = "Timber", Amount = 6 },
		},
	},
	{
		Id = "weekly_supply_sweep",
		Category = "Weekly",
		Name = "Supply Sweep",
		Description = "Extract 10 rewards from corridor runs.",
		Objective = { Type = "ReachDepth", Target = 10, DepthBand = "Shallow" },
		Rewards = {
			{ Type = "Currency", Amount = 750 },
			{ Type = "Food", Key = "Rice", Amount = 8 },
			{ Type = "Material", Key = "Timber", Amount = 8 },
		},
	},
	{
		Id = "weekly_midline_patrol",
		Category = "Weekly",
		Name = "Midline Patrol",
		Description = "Extract 2 rewards from Mid depth or deeper.",
		Objective = { Type = "ReachDepth", Target = 2, DepthBand = "Mid" },
		Rewards = {
			{ Type = "Currency", Amount = 850 },
			{ Type = "Material", Key = "Iron", Amount = 2 },
			{ Type = "Food", Key = "Meat", Amount = 2 },
		},
	},
	{
		Id = "weekly_recruit_shift",
		Category = "Weekly",
		Name = "Recruit Shift",
		Description = "Extract 5 crew members from corridor runs.",
		Objective = { Type = "ExtractCrew", Target = 5 },
		Rewards = {
			{ Type = "Currency", Amount = 800 },
			{ Type = "Food", Key = "Apple", Amount = 6 },
			{ Type = "Material", Key = "Timber", Amount = 5 },
		},
	},
	{
		Id = "weekly_treasure_sprint",
		Category = "Weekly",
		Name = "Treasure Sprint",
		Description = "Open 8 treasure chests.",
		Objective = { Type = "OpenChest", Target = 8 },
		Rewards = {
			{ Type = "Currency", Amount = 650 },
			{ Type = "Food", Key = "Rice", Amount = 5 },
			{ Type = "Material", Key = "Timber", Amount = 8 },
		},
	},
	{
		Id = "weekly_training_push",
		Category = "Weekly",
		Name = "Training Push",
		Description = "Gain 3 crew levels by feeding crew members.",
		Objective = { Type = "UpgradeCrew", Target = 3 },
		Rewards = {
			{ Type = "Currency", Amount = 700 },
			{ Type = "Food", Key = "Meat", Amount = 2 },
			{ Type = "Material", Key = "Iron", Amount = 1 },
		},
	},
}
